# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6553e17df6c3b83c5d85a39026c25771e8e0eca0f6d5dd8561eaf1f60ff19bceaff057a0acb6514c528451052336d17c26f16cff497b414ff3d52dd80f6ca55f

test:
  secret_key_base: b77ac50f3d66a8fd0ba1a30ba234e404cf65abdb3b736015c7fd27a18308758959f94766983c14517ac500b2fc66bfc872b61e7afaca504408ac04b134580b41

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
